/* gen-puzzles.js — generates verified mate-in-1/2/3 puzzles by playing
   semi-random games and scanning positions with the exact mate solver.
   Every emitted puzzle is engine-verified; mate-in-2/3 require a unique
   first move. Regenerate with:
     jsc chess-engine.js gen-puzzles.js > puzzles-data.js */
(function () {
  'use strict';
  const E = ChessEngine;
  const TARGET = { 1: 40, 2: 35, 3: 15 };
  const TIME_LIMIT_MS = 300000;
  const found = { 1: [], 2: [], 3: [] };
  const seen = new Set();
  const t0 = Date.now();

  function pieceCount(board) {
    let n = 0;
    for (let sq = 0; sq < 128; sq++) {
      if (sq & 0x88) { sq += 7; continue; }
      if (board[sq]) n++;
    }
    return n;
  }
  const uci = m => E.sqToAlg(m.from) + E.sqToAlg(m.to) + (m.promotion ? m.promotion.toLowerCase() : '');
  const done = () => found[1].length >= TARGET[1] && found[2].length >= TARGET[2] && found[3].length >= TARGET[3];

  let games = 0;
  while (!done() && Date.now() - t0 < TIME_LIMIT_MS) {
    games++;
    let st = E.initialState();
    const got = {};
    for (let ply = 0; ply < 160; ply++) {
      const moves = E.legalMoves(st);
      if (!moves.length || st.halfmove >= 100) break;

      if (ply >= 8) {
        const key = E.fenKey(st);
        if (!seen.has(key)) {
          const pc = pieceCount(st.board);
          const m1 = E.mateMoves(st, 1, true);
          if (m1.length) {
            if (!got[1] && found[1].length < TARGET[1]) {
              found[1].push({ fen: key, mateIn: 1, rating: 350 + pc * 20, best: uci(m1[0]) });
              got[1] = true;
              seen.add(key);
            }
          } else {
            const m2 = E.mateMoves(st, 3);
            if (m2.length === 1) {
              if (!got[2] && found[2].length < TARGET[2]) {
                found[2].push({ fen: key, mateIn: 2, rating: 800 + pc * 15, best: uci(m2[0]) });
                got[2] = true;
                seen.add(key);
              }
            } else if (!m2.length && pc <= 16 && !got[3] && found[3].length < TARGET[3]) {
              const m3 = E.mateMoves(st, 5);
              if (m3.length === 1) {
                found[3].push({ fen: key, mateIn: 3, rating: 1300 + pc * 12, best: uci(m3[0]) });
                got[3] = true;
                seen.add(key);
              }
            }
          }
        }
      }

      // Half random, half greedy keeps games sharp enough to reach mates.
      const m = Math.random() < 0.5
        ? moves[Math.floor(Math.random() * moves.length)]
        : E.bestMove(st, 1);
      st = E.makeMove(st, m);
    }
  }

  const all = found[1].concat(found[2], found[3]);
  print('/* puzzles-data.js — generated by gen-puzzles.js: ' + all.length + ' engine-verified puzzles');
  print('   (' + found[1].length + ' mate-in-1, ' + found[2].length + ' mate-in-2, ' + found[3].length + ' mate-in-3; ' + games + ' games scanned)');
  print('   Regenerate with: jsc chess-engine.js gen-puzzles.js > puzzles-data.js */');
  print('const PUZZLES = ' + JSON.stringify(all) + ';');
})();
